variables:
   GIT_SUBMODULE_STRATEGY: recursive
   ORD_SOUMET_W: "60"
   ORD_SOUMET_C: "5"
   ORD_SOUMET_M: "8G"
   ORD_SOUMET_TMPFS: "1G"
   
.env:
   build:
      - echo "No specific environment"
   variables:
      ALLOW_FAILURE_ARCHS: ""

include:
   - project: 'RPN-SI/ci-admin'
     ref: dev
     file: '/ci/.gitlab-ci-config.yml'

# ----- TODO : cleanup builds more than 7-day old
# cleanup:u2:
#    stage: cleanup
#    tags:
#       - concurrent
#    script:
#       - find ${ECCI_BUILD_DIR}/precaution -type d -mtime +7 -exec rm -rfv {} \; || true

deploy:staging:
   stage: deploy
   tags:
      - concurrent
   only:
      - master
      - alpha
      - tags
      - /^dev.*$/
      - schedules
   script:
      - ~/ci-admin-bundle/bin/ci-stage-ssm.sh libs rmn "${CI_COMMIT_TAG}" "${ECCI_PROCESS}"

trigger:
   stage: trigger
   only:
      - master
      - alpha
      - /^dev.*$/
      - tags
      - schedules
   script:
      - curl -X POST -F token=${ECCI_TRIGGER_TDPACK}    -F ref=${ECCI_VERSION_TDPACK} -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/6369/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_RPNTOOLS}  -F ref=${ECCI_VERSION_RPNTOOLS} -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/7158/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_BURPTOOLS} -F ref=${ECCI_VERSION_BURPTOOLS} -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/7167/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_GOSSIP}    -F ref=${ECCI_VERSION_GOSSIP} -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/4332/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_EZINTERPV} -F ref=${ECCI_VERSION_EZINTERPV} -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/4302/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_RDIAG}     -F ref=${ECCI_VERSION_RDIAG} -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/4300/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_LIBGRAPH}  -F ref=${ECCI_VERSION_LIBGRAPH} -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/4311/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_IDLFSTD}   -F ref=${ECCI_VERSION_IDLFSTD} -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/4345/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_XREC}      -F ref=${ECCI_VERSION_XREC} -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/4350/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_XVOIR}     -F ref=${ECCI_VERSION_XVOIR} -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/4348/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_GDAL}      -F ref=${ECCI_VERSION_GDAL} -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/7211/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_RANDOM}    -F ref=${ECCI_VERSION_RANDOMTOOLS} -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/7260/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_RPNCOMM}   -F ref=${ECCI_VERSION_RPNCOMM} -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/4298/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_SPOOKI}    -F ref=master -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS}  https://gitlab.science.gc.ca/api/v4/projects/2406/trigger/pipeline
