variables:
   GIT_SUBMODULE_STRATEGY: recursive
   ORD_SOUMET_W: "10"
   ORD_SOUMET_C: "4"
   ORD_SOUMET_M: "8G"
   ORD_SOUMET_TMPFS: "1G"
   ECCI_TRIGGER_FSTTOOLS : a1bf9df63799d00ea5acd683d28e8f
   ECCI_TRIGGER_RPNTOOLS : 786824484e5ee7ad7afe09168f9d57
   ECCI_TRIGGER_BURPTOOLS: 491ef78d8f9d3d842324dc9c26a327
   ECCI_TRIGGER_VGRID    : 97db9f3ad91882b866da2ec8bf4f4b
   ECCI_TRIGGER_RDIAG    : b809c7d38d91eb5c785584c8dd852b
   ECCI_TRIGGER_LIBGRAPH : 654ff2f129d9ac50e494d47f8055b1
   ECCI_TRIGGER_IDLFSTD  : ae646b45425ea987ef473021d7f8df
   ECCI_TRIGGER_XREC     : 1575941b124a67ee15ef63d26e7d47
   ECCI_TRIGGER_XVOIR    : fadfba6698db706df64ab6d9e0255e
   ECCI_TRIGGER_GDAL     : 49ee6127258506ff3c41b4f5d25922
   
stages:
   - build
   - test
   - package
   - deploy
   - trigger

before_script:
   # Force color CMake output even when output is not TTY
   - export CLICOLOR_FORCE=true
   - if [[ ${CI_COMMIT_REF_NAME} == "dev" && ${ECCI_PROCESS:0:3} != "dev" && ${ECCI_PROCESS} != "nightly" ]]; then ECCI_PROCESS="dev_${CI_PIPELINE_ID}"; fi

build:amd64-gnu-9.3.0:
   stage: build
   only:
     - master
     - dev
     - tags
   script:
      - set +e
      - source ci-env/latest/rhel-8-amd-64/gnu-9.3.0.sh 
      - set -e
      - mkdir build_amd64-gnu-9.3.0
      - cd build_amd64-gnu-9.3.0
      - cmake ../
      - time make -j $NCPUS
   artifacts:
      expire_in: 2 hrs
      paths:
         - build_amd64-gnu-9.3.0

build:icelake-gnu-12.1.0:
   stage: build
   only:
     - master
     - dev
     - tags
   script:
      - source ci-env/latest/profile.sh
      - export MODULEPATH=~sidr000/modules:$MODULEPATH
      - module load gcc12
      - export EC_ARCH=rhel-8-icelake-64/gnu-12.1.0
      - echo "========================================================="
      - env | sort
      - echo "========================================================="
      # Loading the compiler via SSM or r.load.dot does not
      # set EC_ARCH, so we set it manually
      - mkdir build_icelake-gnu-12.1.0
      - cd build_icelake-gnu-12.1.0
      - cmake ../
      - time make -j $NCPUS
   artifacts:
      expire_in: 2 hrs
      paths:
         - build_icelake-gnu-12.1.0

build:icelake-inteloneapi-2022.1.2:
   stage: build
   only:
     - master
     - dev
     - tags
   script:
      - set +e
      - source ci-env/latest/rhel-8-icelake-64/inteloneapi-2022.1.2.sh
      - set -e
      - mkdir build_icelake-inteloneapi-2022.1.2
      - cd build_icelake-inteloneapi-2022.1.2
      - cmake ../
      - time make -j $NCPUS
   artifacts:
      expire_in: 2 hrs
      paths:
         - build_icelake-inteloneapi-2022.1.2

build:amd64-inteloneapi-2022.1.2:
   stage: build
   only:
     - master
     - dev
     - tags
   script:
      - set +e
      - source ci-env/latest/rhel-8-amd-64/inteloneapi-2022.1.2.sh
      - set -e
      - mkdir build_amd64-inteloneapi-2022.1.2
      - cd build_amd64-inteloneapi-2022.1.2
      - cmake ../
      - time make -j $NCPUS
   artifacts:
      expire_in: 2 hrs
      paths:
         - build_amd64-inteloneapi-2022.1.2

build:ubuntu-18.04_amd64_inteloneapi-2022.1.2:
   variables:
      ORD_SOUMET_MACH    : gpsc1
      ORD_SOUMET_IMAGE   : eccc/eccc_all_default_ubuntu-18.04-amd64_latest
      ORD_SOUMET_PROJECT : eccc_mrd
   stage: build
   only:
     - master
     - dev
     - tags
   script:
      - set +e
      - source ci-env/latest/ubuntu-18.04-amd-64/inteloneapi-2022.1.2.sh
      - set -e
      - mkdir build_ubuntu-18.04_amd64_inteloneapi-2022.1.2
      - cd build_ubuntu-18.04_amd64_inteloneapi-2022.1.2
      - cmake ../
      - time make -j $NCPUS
   artifacts:
      expire_in: 2 hrs
      paths:
         - build_ubuntu-18.04_amd64_inteloneapi-2022.1.2

test:amd64-gnu-9.3.0:
   stage: test
   only:
     - master
     - dev
     - tags
   dependencies:
     - build:amd64-gnu-9.3.0
   script:
      - set +e
      - source ci-env/latest/profile.sh
      - set -e
      - cd build_amd64-gnu-9.3.0
      - make test

test:icelake-gnu-12.1.0:
   stage: test
   only:
     - master
     - dev
     - tags
   dependencies:
     - build:icelake-gnu-12.1.0
   script:
      - set +e
      - source ci-env/latest/profile.sh
      - set -e
      - cd build_icelake-gnu-12.1.0
      - make test

test:icelake-inteloneapi-2022.1.2:
   stage: test
   only:
     - master
     - dev
     - tags
   dependencies:
     - build:icelake-inteloneapi-2022.1.2
   script:
      - set +e
      - source ci-env/latest/rhel-8-icelake-64/inteloneapi-2022.1.2.sh
      - set -e
      - cd build_icelake-inteloneapi-2022.1.2
      - make test

test:amd64-inteloneapi-2022.1.2:
   stage: test
   only:
     - master
     - dev
     - tags
   dependencies:
     - build:amd64-inteloneapi-2022.1.2
   script:
      - set +e
      - source ci-env/latest/rhel-8-amd-64/inteloneapi-2022.1.2.sh
      - set -e
      - cd build_amd64-inteloneapi-2022.1.2
      - make test

package:amd64-gnu-9.3.0:
   stage: package
   only:
      - master
      - dev
      - tags
      - schedules
   dependencies:
      - build:amd64-gnu-9.3.0
   environment:
      name: testing
   script:
      - set +e
      - source ci-env/latest/rhel-8-amd-64/gnu-9.3.0.sh
      - set -e
      - cd build_amd64-gnu-9.3.0
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

package:icelake-inteloneapi-2022.1.2:
   stage: package
   only:
      - master
      - dev
      - tags
      - schedules
   dependencies:
      - build:icelake-inteloneapi-2022.1.2
   environment:
      name: testing
   script:
      - set +e
      - source ci-env/latest/rhel-8-icelake-64/inteloneapi-2022.1.2.sh
      - set -e
      - cd build_icelake-inteloneapi-2022.1.2
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

package:amd64-inteloneapi-2022.1.2:
   stage: package
   only:
      - master
      - dev
      - tags
      - schedules
   dependencies:
      - build:amd64-inteloneapi-2022.1.2
   environment:
      name: testing
   script:
      - set +e
      - source ci-env/latest/rhel-8-amd-64/inteloneapi-2022.1.2.sh
      - set -e
      - cd build_amd64-inteloneapi-2022.1.2
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

package:ubuntu-18.04_amd64_inteloneapi-2022.1.2:
   variables:
      ORD_SOUMET_MACH    : gpsc1
      ORD_SOUMET_IMAGE   : eccc/eccc_all_default_ubuntu-18.04-amd64_latest
      ORD_SOUMET_PROJECT : eccc_mrd
   stage: package
   only:
      - master
      - dev
      - tags
      - schedules
   dependencies:
      - build:ubuntu-18.04_amd64_inteloneapi-2022.1.2
   environment:
      name: testing
   script:
      - set +e
      - source ci-env/latest/ubuntu-18.04-amd-64/inteloneapi-2022.1.2.sh
      - set -e
      - cd build_ubuntu-18.04_amd64_inteloneapi-2022.1.2
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

deploy:staging:
   stage: deploy
   only:
      - master
      - tags
      - dev
      - schedules
   script:
      - ~/ci-admin-bundle/bin/ci-stage-ssm.sh libs rmn "${CI_COMMIT_TAG}" "${ECCI_PROCESS}"

trigger:
   stage: trigger
   only:
      - master
      - dev
      - tags
      - schedules
   script:
      - curl -X POST -F token=${ECCI_TRIGGER_FSTTOOLS}  -F ref=dev -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/6032/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_RPNTOOLS}  -F ref=dev -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/7158/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_BURPTOOLS} -F ref=dev -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/7167/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_VGRID}     -F ref=dev -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/114/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_RDIAG}     -F ref=dev -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/4300/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_LIBGRAPH}  -F ref=dev -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/4311/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_IDLFSTD}   -F ref=dev -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/4345/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_XREC}      -F ref=dev -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/4350/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_XVOIR}     -F ref=dev -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/4348/trigger/pipeline
      - curl -X POST -F token=${ECCI_TRIGGER_GDAL}      -F ref=dev -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/7211/trigger/pipeline
