variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_gpsc:
  stage: build
  script: ssh eccc-gpsc1.science.gc.ca $CI_PROJECT_DIR/ci_build $CI_PROJECT_DIR
  only:
    - master
    - dev

build_ppp:
  stage: build
  script: ssh ppp3.science.gc.ca $CI_PROJECT_DIR/ci_build $CI_PROJECT_DIR
  only:
    - master
    - dev

build_xc:
  stage: build
  script: ssh daley.science.gc.ca $CI_PROJECT_DIR/ci_build $CI_PROJECT_DIR
  only:
    - master
    - dev

