variables:
   GIT_SUBMODULE_STRATEGY: recursive
   ORD_SOUMET_W: "10"
   ORD_SOUMET_C: "20"
   ORD_SOUMET_M: "100G"
   ORD_SOUMET_TMPFS: "10G"

stages:
   - build
   - test
   - package
   - deploy

before_script:
   # Force color CMake output even when output is not TTY
   - export CLICOLOR_FORCE=true

#build_gpsc:
#  stage: build
#  script: ssh eccc-gpsc1.science.gc.ca $CI_PROJECT_DIR/ci_build $CI_PROJECT_DIR
#  only:
#    - master
#    - dev

build:XC50_intel-19.0.3:
   stage: build
   tags:
      - XC50-login
   only:
      - master
      - dev
      - tags
   script:
      - set +e
      - source ci-env/latest/sles-15-skylake-64/intel-19.0.3.199.sh
      - set -e
      - mkdir build_XC50_intel-19.0.3
      - cd build_XC50_intel-19.0.3
      - cmake ../ 
      - make
   artifacts:
      expire_in: 2 hrs
      paths:
         - build_XC50_intel-19.0.3

build:XC50_intel-19.0.5:
   stage: build
   tags:
      - XC50-login
   only:
#      - master
#      - dev
#      - tags
   script:
      - set +e
      - source ci-env/latest/sles-15-skylake-64/intel-19.0.5.281.sh
      - set -e
      - mkdir build_XC50_intel-19.0.5
      - cd build_XC50_intel-19.0.5
      - cmake ../ 
      - make
   artifacts:
      expire_in: 2 hrs
      paths:
         - build_XC50_intel-19.0.5

build:skylake-intel-19.0.3:
   stage: build
   only:
#      - master
#      - dev
#      - tags
   script:
      - source ci-env/latest/ubuntu-18.04-skylake-64/intel-19.0.3.199.sh
      - mkdir build_skylake-intel-19.0.3
      - cd build_skylake-intel-19.0.3
      - cmake ../ 
      - make -j
   artifacts:
      expire_in: 2 hrs
      paths:
         - build_skylake-intel-19.0.3

build:amd-intel-19.0.3:
   stage: build
   only:
#      - master
#      - dev
#      - tags
   script:
      - source ci-env/latest/ubuntu-18.04-amd-64/intel-19.0.3.199.sh
      - mkdir build_amd-intel-19.0.3
      - cd build_amd-intel-19.0.3
      - cmake ../ 
      - make -j
   artifacts:
      expire_in: 2 hrs
      paths:
         - build_amd-intel-19.0.3

build:amd-gnu-7.4.0:
   stage: build
   only:
#      - master
#      - dev
#      - tags
   script:
      - set +e
      - source ci-env/latest/ubuntu-18.04-amd-64/gnu-7.4.0.sh
      - . r.load.dot rpn/libs/19.7.1/tdpack_1.6.0-gnu-7.4.0_ubuntu-18.04-amd64-64
      - set -e
      - mkdir build_amd-gnu-7.4.0
      - cd build_amd-gnu-7.4.0
      - cmake ../ 
      - make -j
   artifacts:
      expire_in: 2 hrs
      paths:
         - build_amd-gnu-7.4.0

#test:skylake-intel-19.0.3:
#   stage: test
#   only:
#      - master
#      - dev
#   script:
#      - source ci-env/latest/ubuntu-18.04-amd-64/intel-19.0.3.199.sh
#      - cd build_skylake-intel-19.0.3
#      - make check

#test:amd-gnu-7.4.0:
#   stage: test
#   only:
#      - master
#      - dev
#   script:
#      - source ci-env/latest/ubuntu-18.04-amd-64/gnu-7.4.0.sh
#      - cd build_amd-gnu-7.4.0
#      - make check

package:XC50_intel-19.0.3:
   stage: package
   tags:
      - XC50-login
   only:
      - tags
   dependencies:
      - build:XC50_intel-19.0.3
   environment:
      name: testing
   script:
      - set +e
      - source ci-env/latest/sles-15-skylake-64/intel-19.0.3.199.sh
      - set -e
      - cd build_XC50_intel-19.0.3
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package

package:XC50_intel-19.0.5:
   stage: package
   tags:
      - XC50-login
   only:
      - tags
   dependencies:
      - build:XC50_intel-19.0.5
   environment:
      name: testing
   script:
      - set +e
      - source ci-env/latest/sles-15-skylake-64/intel-19.0.5.281.sh
      - set -e
      - cd build_XC50_intel-19.0.5
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package

package:skylake-intel-19.0.3:
   stage: package
   only:
      - tags
   dependencies:
      - build:skylake-intel-19.0.3
   environment:
      name: testing
   script:
      - source ci-env/latest/ubuntu-18.04-skylake-64/intel-19.0.3.199.sh
      - cd build_skylake-intel-19.0.3
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package

package:amd-intel-19.0.3:
   stage: package
   only:
      - tags
   dependencies:
      - build:amd-intel-19.0.3
   environment:
      name: testing
   script:
      - source ci-env/latest/ubuntu-18.04-amd-64/intel-19.0.3.199.sh
      - cd build_amd-intel-19.0.3
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package

package:amd-gnu-7.4.0:
   stage: package
   only:
      - tags
   dependencies:
      - build:amd-gnu-7.4.0
   environment:
      name: testing
   script:
      - set +e
      - source ci-env/latest/ubuntu-18.04-amd-64/gnu-7.4.0.sh
      - set -e
      - cd build_amd-gnu-7.4.0
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package

deploy:staging:
   stage: deploy
   only:
      - tags
   script:
      - source ci-env/latest/profile.sh
      - ~/ci-admin-bundle/bin/ci-stage-ssm.sh libs $CI_PROJECT_NAME $CI_COMMIT_TAG
