variables:
   GIT_SUBMODULE_STRATEGY: recursive
   ORD_SOUMET_W: "10"
   ORD_SOUMET_C: "4"
   ORD_SOUMET_M: "8G"
   ORD_SOUMET_TMPFS: "1G"

stages:
   - build
   - test
   - package
   - deploy

before_script:
   # Force color CMake output even when output is not TTY
   - export CLICOLOR_FORCE=true

#build_gpsc:
#  stage: build
#  script: ssh eccc-gpsc1.science.gc.ca $CI_PROJECT_DIR/ci_build $CI_PROJECT_DIR
#  only:
#    - master
#    - dev


build:icelake-gnu-9.3.0:
   stage: build
   only:
#      - master
#      - dev
#      - tags
   script:
      - source ci-env/latest/profile.sh
      - . r.load.dot main/opt/gcc/gcc-9.3.0
      - export EC_ARCH=ubuntu-18.04-icelake-64/gnu-9.3.0
      - echo "========================================================="
      - env | sort
      - echo "========================================================="
      # Loading the compiler via SSM or r.load.dot does not
      # set EC_ARCH, so we set it manually
      - mkdir build_icelake-gnu-9.3.0
      - cd build_icelake-gnu-9.3.0
      - cmake ../
      - time make -j $NCPUS
   artifacts:
      expire_in: 2 hrs
      paths:
         - build_icelake-gnu-9.3.0

build:icelake-gnu-12.1.0:
   stage: build
   only:
#      - master
#      - dev
#      - tags
   script:
      - source ci-env/latest/profile.sh
      - export MODULEPATH=~sidr000/modules:$MODULEPATH
      - module load gcc12
      - export EC_ARCH=ubuntu-18.04-icelake-64/gnu-12.1.0
      - echo "========================================================="
      - env | sort
      - echo "========================================================="
      # Loading the compiler via SSM or r.load.dot does not
      # set EC_ARCH, so we set it manually
      - mkdir build_icelake-gnu-12.1.0
      - cd build_icelake-gnu-12.1.0
      - cmake ../
      - time make -j $NCPUS
   artifacts:
      expire_in: 2 hrs
      paths:
         - build_icelake-gnu-12.1.0

build:icelake-inteloneapi-2022.1.2:
   stage: build
   only:
#      - master
#      - dev
#      - tags
   script:
      - source ci-env/latest/profile.sh
      - . r.load.dot /fs/ssm/eccc/mrd/rpn/code-tools/ENV/cdt-1.5.7-inteloneapi-2022.1.2
      - echo "========================================================="
      - env | sort
      - echo "========================================================="
      # Loading the compiler via SSM or r.load.dot does not
      # set EC_ARCH, so we set it manually
      - mkdir build_icelake-inteloneapi-2022.1.2
      - cd build_icelake-inteloneapi-2022.1.2
      - cmake ../
      - time make -j $NCPUS
   artifacts:
      expire_in: 2 hrs
      paths:
         - build_icelake-inteloneapi-2022.1.2


#test:icelake-intel-19.0.3:
#   stage: test
#   only:
#      - master
#      - dev
#   script:
#      - source ci-env/latest/ubuntu-18.04-amd-64/intel-19.0.3.199.sh
#      - cd build_icelake-intel-19.0.3
#      - make check

#test:amd-gnu-7.4.0:
#   stage: test
#   only:
#      - master
#      - dev
#   script:
#      - source ci-env/latest/ubuntu-18.04-amd-64/gnu-7.4.0.sh
#      - cd build_amd-gnu-7.4.0
#      - make check


package:icelake-gnu-9.3.0:
   stage: package
   only:
      - tags
   dependencies:
      - build:icelake-gnu-9.3.0
   environment:
      name: testing
   script:
      - set +e
      - source ci-env/latest/ubuntu-18.04-amd-64/gnu-7.4.0.sh
      - set -e
      - cd build_icelake-gnu-9.3.0
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package

package:icelake-inteloneapi-2022.1.2:
   stage: package
   only:
      - tags
   dependencies:
      - build:icelake-inteloneapi-2022.1.2
   environment:
      name: testing
   script:
      - set +e
      - source ci-env/latest/ubuntu-18.04-amd-64/gnu-7.4.0.sh
      - set -e
      - cd build_icelake-inteloneapi-2022.1.2
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package

deploy:staging:
   stage: deploy
   only:
      - tags
   script:
      - source ci-env/latest/profile.sh
      - ~/ci-admin-bundle/bin/ci-stage-ssm.sh libs $CI_PROJECT_NAME $CI_COMMIT_TAG
