#!/bin/bash

. /fs/ssm/eccc/mrd/ordenv/profile/1.13.0

case $ORDENV_TRUEHOST in
    eccc-ppp[3,4]|eccc-gpsc1)
	. r.load.dot comm/eccc/all/opt/intelcomp/intelpsxe-cluster-19.0.3.199
	;;
esac

set -o errexit

CI_PROJECT_DIR="$1"

cd "$CI_PROJECT_DIR"

echo "======== Star env ========"
env | sort
echo "======== End env ========"

echo "Current path: $PWD"


echo -e "Starting build ...\n"

mkdir build
cd build
cmake ../librmn -DBUILD_SHARED_LIBS=FALSE
make
