#!/bin/bash
#
# This forms the basis for the xx-config utility, which tells you
# various things about the library installation.

cc=CMAKE_CC
ftn=CMAKE_FTN
cflags=CMAKE_CFLAGS
libs=CMAKE_LIBS

version=CMAKE_VERSION

usage()
{
    cat <<EOF
Usage: CMAKE_NAME-config [OPTION]

Available values for OPTION include:

  --help         display this help message and exit
  --cc           C compiler [${cc}]
  --ftn          FORTRAN compiler [${ftn}]
  --cflags       pre-processor and compiler flags [${cflags}]
  --libs         library linking information for netcdf [${libs}]
  --version      Library version [${version}]

EOF
}

if test $# -eq 0; then
    usage 1
fi

while test $# -gt 0; do
    case "$1" in
    # this deals with options in the style
    # --option=value and extracts the value part
    # [not currently used]
    -*=*) value=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) value= ;;
    esac

    case "$1" in

    --help)
	usage 0
	;;

    --cc)
       	echo ${cc:-no}
       	;;

    --ftn)
       	echo ${ftn:-no}
       	;;

    --clags)
       	echo ${cflags}
       	;;
           
    --libs)
       	echo ${libs}
       	;;

    --version)
	    echo $version
	    ;;

    *)
        echo "unknown option: $1"
	    usage 1
	    ;;
    esac
    shift
done

exit 0
