#!/bin/sh
#
# "slabtest" will read file 1998010700_024 and create
# a slabfile "slabfile1", and also writes the equivalent
# standard file "stdfile1".
# "delamineur" will take "slabfile1" and make a RPN std file "stdfile"
# Compare "stdfile1" with "final.fst" 

\rm final.fst
\rm slabfile1
\rm stdfile1

slabtest
delamineur slabfile1 stdfile1
