#!/bin/ksh
r.compile -O 2 -src RPN_COMM.cdk90 RPN_COMM*.c -mpi
r.compile -O 2 -src RPN_COMM*.f -mpi -openmp
if [[ ${1:-local} = beta ]]
then
  ar rcv ${EC_ARCH}/librpn_commbeta.a *.o
else
  ar rcv librpn_commbeta_${EC_ARCH}.a *.o
fi
\rm *.o
rm *.mod
rm -rf rii_files
cd  ../bmf
./complib "$@"
#for arch in Linux ; do
#  echo $arch
#  make clean; make ARCH=$arch
#  mv RPN*.o $arch;cd $arch ;r.ar -arch $arch cvr librpn_comm.a RPN*.o ; cd ..
#
#done

