interface
    integer function gmm_add_table_entry141(p, key)
        integer*4, pointer :: p(:)
        integer*8, intent(in) :: key
    end function gmm_add_table_entry141


    integer function gmm_get_nxt_avail_ptr141()
    end function gmm_get_nxt_avail_ptr141


    integer function gmm_update_table_entry141(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_table_entry141


    integer function gmm_add_table_entry142(p, key)
        integer*4, pointer :: p(:,:)
        integer*8, intent(in) :: key
    end function gmm_add_table_entry142


    integer function gmm_get_nxt_avail_ptr142()
    end function gmm_get_nxt_avail_ptr142


    integer function gmm_update_table_entry142(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_table_entry142


    integer function gmm_add_table_entry143(p, key)
        integer*4, pointer :: p(:,:,:)
        integer*8, intent(in) :: key
    end function gmm_add_table_entry143


    integer function gmm_get_nxt_avail_ptr143()
    end function gmm_get_nxt_avail_ptr143


    integer function gmm_update_table_entry143(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_table_entry143


    integer function gmm_add_table_entry144(p, key)
        integer*4, pointer :: p(:,:,:,:)
        integer*8, intent(in) :: key
    end function gmm_add_table_entry144


    integer function gmm_get_nxt_avail_ptr144()
    end function gmm_get_nxt_avail_ptr144


    integer function gmm_update_table_entry144(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_table_entry144


    integer function gmm_add_table_entry181(p, key)
        integer*8, pointer :: p(:)
        integer*8, intent(in) :: key
    end function gmm_add_table_entry181


    integer function gmm_get_nxt_avail_ptr181()
    end function gmm_get_nxt_avail_ptr181


    integer function gmm_update_table_entry181(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_table_entry181


    integer function gmm_add_table_entry182(p, key)
        integer*8, pointer :: p(:,:)
        integer*8, intent(in) :: key
    end function gmm_add_table_entry182


    integer function gmm_get_nxt_avail_ptr182()
    end function gmm_get_nxt_avail_ptr182


    integer function gmm_update_table_entry182(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_table_entry182


    integer function gmm_add_table_entry183(p, key)
        integer*8, pointer :: p(:,:,:)
        integer*8, intent(in) :: key
    end function gmm_add_table_entry183


    integer function gmm_get_nxt_avail_ptr183()
    end function gmm_get_nxt_avail_ptr183


    integer function gmm_update_table_entry183(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_table_entry183


    integer function gmm_add_table_entry184(p, key)
        integer*8, pointer :: p(:,:,:,:)
        integer*8, intent(in) :: key
    end function gmm_add_table_entry184


    integer function gmm_get_nxt_avail_ptr184()
    end function gmm_get_nxt_avail_ptr184


    integer function gmm_update_table_entry184(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_table_entry184


    integer function gmm_add_table_entry241(p, key)
        real*4, pointer :: p(:)
        integer*8, intent(in) :: key
    end function gmm_add_table_entry241


    integer function gmm_get_nxt_avail_ptr241()
    end function gmm_get_nxt_avail_ptr241


    integer function gmm_update_table_entry241(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_table_entry241


    integer function gmm_add_table_entry242(p, key)
        real*4, pointer :: p(:,:)
        integer*8, intent(in) :: key
    end function gmm_add_table_entry242


    integer function gmm_get_nxt_avail_ptr242()
    end function gmm_get_nxt_avail_ptr242


    integer function gmm_update_table_entry242(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_table_entry242


    integer function gmm_add_table_entry243(p, key)
        real*4, pointer :: p(:,:,:)
        integer*8, intent(in) :: key
    end function gmm_add_table_entry243


    integer function gmm_get_nxt_avail_ptr243()
    end function gmm_get_nxt_avail_ptr243


    integer function gmm_update_table_entry243(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_table_entry243


    integer function gmm_add_table_entry244(p, key)
        real*4, pointer :: p(:,:,:,:)
        integer*8, intent(in) :: key
    end function gmm_add_table_entry244


    integer function gmm_get_nxt_avail_ptr244()
    end function gmm_get_nxt_avail_ptr244


    integer function gmm_update_table_entry244(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_table_entry244


    integer function gmm_add_table_entry281(p, key)
        real*8, pointer :: p(:)
        integer*8, intent(in) :: key
    end function gmm_add_table_entry281


    integer function gmm_get_nxt_avail_ptr281()
    end function gmm_get_nxt_avail_ptr281


    integer function gmm_update_table_entry281(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_table_entry281


    integer function gmm_add_table_entry282(p, key)
        real*8, pointer :: p(:,:)
        integer*8, intent(in) :: key
    end function gmm_add_table_entry282


    integer function gmm_get_nxt_avail_ptr282()
    end function gmm_get_nxt_avail_ptr282


    integer function gmm_update_table_entry282(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_table_entry282


    integer function gmm_add_table_entry283(p, key)
        real*8, pointer :: p(:,:,:)
        integer*8, intent(in) :: key
    end function gmm_add_table_entry283


    integer function gmm_get_nxt_avail_ptr283()
    end function gmm_get_nxt_avail_ptr283


    integer function gmm_update_table_entry283(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_table_entry283


    integer function gmm_add_table_entry284(p, key)
        real*8, pointer :: p(:,:,:,:)
        integer*8, intent(in) :: key
    end function gmm_add_table_entry284


    integer function gmm_get_nxt_avail_ptr284()
    end function gmm_get_nxt_avail_ptr284


    integer function gmm_update_table_entry284(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_table_entry284


    integer function gmm_add_table_entry381(p, key)
        complex*8, pointer :: p(:)
        integer*8, intent(in) :: key
    end function gmm_add_table_entry381


    integer function gmm_get_nxt_avail_ptr381()
    end function gmm_get_nxt_avail_ptr381


    integer function gmm_update_table_entry381(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_table_entry381


    integer function gmm_add_table_entry382(p, key)
        complex*8, pointer :: p(:,:)
        integer*8, intent(in) :: key
    end function gmm_add_table_entry382


    integer function gmm_get_nxt_avail_ptr382()
    end function gmm_get_nxt_avail_ptr382


    integer function gmm_update_table_entry382(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_table_entry382


    integer function gmm_add_table_entry383(p, key)
        complex*8, pointer :: p(:,:,:)
        integer*8, intent(in) :: key
    end function gmm_add_table_entry383


    integer function gmm_get_nxt_avail_ptr383()
    end function gmm_get_nxt_avail_ptr383


    integer function gmm_update_table_entry383(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_table_entry383


    integer function gmm_add_table_entry384(p, key)
        complex*8, pointer :: p(:,:,:,:)
        integer*8, intent(in) :: key
    end function gmm_add_table_entry384


    integer function gmm_get_nxt_avail_ptr384()
    end function gmm_get_nxt_avail_ptr384


    integer function gmm_update_table_entry384(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_table_entry384
end interface
