#!/usr/bin/env python3

import argparse
import json
from pathlib import Path
from urllib.parse import urlparse

import numpy as np

import rmn.virtualizarr


def main():
    parser = argparse.ArgumentParser(
        description="Simulate a third-party application using librmn's VirtualiZarr codec (Pure Python Emulation)."
    )
    parser.add_argument(
        "manifest",
        type=Path,
        help="Kerchunk manifest generated by rmn.virtualizarr.generate_manifest()",
    )
    args = parser.parse_args()

    #rmn.virtualizarr.register_codec()

    print("[1] Opening VirtualiZarr manifest ...")
    with open(args.manifest, "r", encoding="utf-8") as f:
        manifest_data = json.load(f)

    refs = manifest_data.get("refs", {})
    variables = list(dict.fromkeys(key.split("/")[0] for key in refs.keys() if "/" in key))

    print("\nVariables found in manifest:")
    print(variables)

    if not variables:
        raise RuntimeError("Dataset contains no variables.")

    var = variables[9]
    print(f"\n[2] Accessing '{var}'")

    zarray = json.loads(refs[f"{var}/.zarray"])
    backend = zarray["compressor"]["backend"]
    order = zarray["order"]
    shape = zarray["shape"]
    dtype = np.dtype(zarray["dtype"])

    chunk_ref = refs[f"{var}/0.0.0"]
    file_uri, byte_offset, byte_length = chunk_ref

    print(f"  -> VirtualiZarr target URI: {file_uri}")
    print(f"  -> Offset: {byte_offset} bytes, Length: {byte_length} bytes")

    local_path = urlparse(file_uri).path
    print(f"  -> Reading raw bytes from: {local_path}")
    with open(local_path, "rb") as fst_f:
        fst_f.seek(byte_offset)
        raw_bytes = fst_f.read(byte_length)

    print("  -> numcodecs calls Fst24Codec.decode()")
    codec = rmn.virtualizarr.Fst24Codec(backend=backend, order=order)
    decoded_bytes = codec.decode(raw_bytes)

    data = np.frombuffer(decoded_bytes, dtype=dtype).reshape(shape, order=order)

    print("\nDecoded successfully")
    print(f"shape = {data.shape}")
    print(f"dtype = {data.dtype}")
    print(f"min = {data.min()}")
    print(f"max = {data.max()}")

    assert isinstance(data, np.ndarray)
    print("\nSuccess!")


if __name__ == "__main__":
    main()
