
      PROGRAM ADVECT
C
C     ANDRE ROBERT.     OCTOBRE 1984.
C
C     TRANSLATION EN UNE DIMENSION. ETUDE DE
C     L'INSTABILITE NUMERIQUE ET DES PROBLEMES
C     ASSOCIES AUX FRONTIERES LATERALES.
C
C     C=U*DT/DX   NOMBRE DE COURANT.
C     NI=NOMBRE DE POINTS DE GRILLE.
C     NC=0 COURBE PLATE F(I)=50.0
C     NC=1 COURBE GAUSSIENNE.
C     NS=0 POINT DE SORTIE FIXE F(NI)=0
C     NS=1 POINT DE SORTIE VARIABLE EN FONCTION DU TEMPS.
C     NR=RUN NUMBER.
C
      C=1.2
      NI=241
      NC=1
      NS=0
      NR=1
C
C     CAS #1  INTEGRATION INSTABLE.
      CALL RUNADV (C,NI,NC,NS,NR)
C
C     CAS #2  INTEGRATION STABLE.
C     CALL RUNADV (0.5,NI,NC,NS,2)
C
C     CAS #3  PROBLEME A LA FRONTIERE DE SORTIE.
C     CALL RUNADV (0.5,101,NC,NS,3)
C
C     CAS #4  PROBLEME AVEC COURBE PLATE.
C     CALL RUNADV (0.5,101,0,NS,4)
C
C     CAS #5  FRONTIERE DE SORTIE VARIABLE.
C     CALL RUNADV (0.5,101,1,1,5)
C
      STOP
      END

      SUBROUTINE RUNADV (C,NI,NC,NS,NR)
      DIMENSION F(241,121),X(241)
C
C     ANDRE ROBERT.     OCTOBRE 1984.
C
      CALL DATA1 (F,NI,81,NC,NR)
C
      CALL MODEL (F,NI,80,C,NS)
C
      DO 1 N=1,241
    1 X(N)=N
C
      IF (NR.NE.1) GO TO 2
      CALL ECRIT2 (X,F,NI,NR,20,26,28,30,32)
      RETURN
    2 CALL ECRIT2 (X,F,NI,NR,0,20,40,60,80)
C
      RETURN
      END

      SUBROUTINE DATA1 (F,NI,NT,NC,NR)
      DIMENSION F(NI,NT)
C
C     ANDRE ROBERT.     OCTOBRE 1984.
C
      A=8.0
      IF (NR.GE.3) A=20.0
      I0=81
      IF (NR.GE.3) I0=51
      NIM=NI-1
C
      DO 1 N=1,NT
      F(1,N)=0.0
      F(NI,N)=0.0
    1 CONTINUE
C
      DO 2 I=2,NIM
      F(I,1)=100*EXP(-(I-I0)**2/(A*A))
      IF (NC.EQ.0) F(I,1)=50.0
    2 CONTINUE
C
      RETURN
      END

      SUBROUTINE MODEL (F,NI,NT,C,NS)
      DIMENSION F(NI,100)
C
C     ANDRE ROBERT.     OCTOBRE 1984.
C
      NIM=NI-1
C
      DO 1 I=2,NIM
      F(I,2)=F(I,1)-C/2.0*(F(I+1,1)-F(I-1,1))
    1 CONTINUE
C
C
      DO 3 N=2,NT
      DO 2 I=2,NIM
      F(I,N+1)=F(I,N-1)-C*(F(I+1,N)-F(I-1,N))
    2 CONTINUE
    3 CONTINUE
C
      RETURN
      END

      SUBROUTINE ECRIT2 (X,F,NI,NR,N1,N2,N3,N4,N5)
      DIMENSION X(NI),F(NI,100)
      COMMON /BOX/KX,KY,XL,XH,YL,YH
      CHARACTER LBLX*18,LBLY*19
      LBLY='   FONCTION F(X)   '
      LBLX='  POINT DE GRILLE '
C
C     ANDRE ROBERT.     OCTOBRE 1984.
C
      KX=490
      KY=290
      XL=1.0
      XH=NI
      YL=-50.0
      YH=150.0
C
      NA=N1+1
      NB=N2+1
      NC=N3+1
      ND=N4+1
      NE=N5+1
C
      NT=N1
      CALL COURBE (X,F(1,NA),NI,1,1)
      NT=N2
      CALL COURBE (X,F(1,NB),NI,1,1)
      NT=N3
      CALL COURBE (X,F(1,NC),NI,1,1)
      NT=N4
      CALL COURBE (X,F(1,ND),NI,1,1)
      NT=N5
      CALL COURBE (X,F(1,NE),NI,1,1)
C
      RETURN
      END
