
module rmn_burpopt
    use rmn_burp_defi, only: MAXREP, RMANQUE
    implicit none
    save

    REAL :: MANQUE = RMANQUE !< VALEUR A DONNER AUX VALEURS REELLES MANQUANTES

    !> VECTEUR DE BITS OU UN BIT ALLUME INDIQUE QUE L'ELEMENT POURTANT LE NUMERO DU BIT EST REPETITIF
    INTEGER, dimension(MAXREP) :: RPETITIF = 0

    !> PREND LA VALEUR 1 LORSQU'ON UTILISE UNE AUTRE TABLE QE LA TABLEBURP OFFICIELLE
    INTEGER :: BADTBL = 0

end module rmn_burpopt
