integer function gmm_update_tpi_key2(indx, datatype, key)
    implicit none
    integer, intent(in) :: indx, datatype
    integer*8, intent(in) :: key

    include "gmm_pointer_table_interface.inc"

    select case (datatype)
        case (184)
            gmm_update_tpi_key2 = gmm_update_table_entry184(indx, key)
        case (144)
            gmm_update_tpi_key2 = gmm_update_table_entry144(indx, key)
        case (284)
            gmm_update_tpi_key2 = gmm_update_table_entry284(indx, key)
        case (244)
            gmm_update_tpi_key2 = gmm_update_table_entry244(indx, key)
        case (384)
            gmm_update_tpi_key2 = gmm_update_table_entry384(indx, key)
        case (183)
            gmm_update_tpi_key2 = gmm_update_table_entry183(indx, key)
        case (143)
            gmm_update_tpi_key2 = gmm_update_table_entry143(indx, key)
        case (283)
            gmm_update_tpi_key2 = gmm_update_table_entry283(indx, key)
        case (243)
            gmm_update_tpi_key2 = gmm_update_table_entry243(indx, key)
        case (383)
            gmm_update_tpi_key2 = gmm_update_table_entry383(indx, key)
        case (182)
            gmm_update_tpi_key2 = gmm_update_table_entry182(indx, key)
        case (142)
            gmm_update_tpi_key2 = gmm_update_table_entry142(indx, key)
        case (282)
            gmm_update_tpi_key2 = gmm_update_table_entry282(indx, key)
        case (242)
            gmm_update_tpi_key2 = gmm_update_table_entry242(indx, key)
        case (382)
            gmm_update_tpi_key2 = gmm_update_table_entry382(indx, key)
        case (181)
            gmm_update_tpi_key2 = gmm_update_table_entry181(indx, key)
        case (141)
            gmm_update_tpi_key2 = gmm_update_table_entry141(indx, key)
        case (281)
            gmm_update_tpi_key2 = gmm_update_table_entry281(indx, key)
        case (241)
            gmm_update_tpi_key2 = gmm_update_table_entry241(indx, key)
        case (381)
            gmm_update_tpi_key2 = gmm_update_table_entry381(indx, key)
    end select
end function gmm_update_tpi_key2
