interface
    integer function gmm_checkpoint_all(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_all

    integer function gmm_checkpoint_184(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_184

    integer function gmm_checkpoint_144(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_144

    integer function gmm_checkpoint_284(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_284

    integer function gmm_checkpoint_244(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_244

    integer function gmm_checkpoint_384(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_384

    integer function gmm_checkpoint_183(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_183

    integer function gmm_checkpoint_143(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_143

    integer function gmm_checkpoint_283(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_283

    integer function gmm_checkpoint_243(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_243

    integer function gmm_checkpoint_383(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_383

    integer function gmm_checkpoint_182(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_182

    integer function gmm_checkpoint_142(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_142

    integer function gmm_checkpoint_282(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_282

    integer function gmm_checkpoint_242(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_242

    integer function gmm_checkpoint_382(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_382

    integer function gmm_checkpoint_181(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_181

    integer function gmm_checkpoint_141(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_141

    integer function gmm_checkpoint_281(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_281

    integer function gmm_checkpoint_241(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_241

    integer function gmm_checkpoint_381(write)
        !> Write to checkpoint file when true.  Otherwise, read.
        logical write
    end function gmm_checkpoint_381
end interface
