interface gmm_update_tpi_key
    integer function gmm_update_tpi_key2(indx, datatype, key)
        integer, intent(in) :: indx, datatype
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key2

    integer function gmm_update_tpi_key184(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key184

    integer function gmm_update_tpi_key144(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key144

    integer function gmm_update_tpi_key284(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key284

    integer function gmm_update_tpi_key244(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key244

    integer function gmm_update_tpi_key384(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key384

    integer function gmm_update_tpi_key183(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key183

    integer function gmm_update_tpi_key143(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key143

    integer function gmm_update_tpi_key283(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key283

    integer function gmm_update_tpi_key243(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key243

    integer function gmm_update_tpi_key383(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key383

    integer function gmm_update_tpi_key182(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key182

    integer function gmm_update_tpi_key142(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key142

    integer function gmm_update_tpi_key282(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key282

    integer function gmm_update_tpi_key242(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key242

    integer function gmm_update_tpi_key382(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key382

    integer function gmm_update_tpi_key181(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key181

    integer function gmm_update_tpi_key141(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key141

    integer function gmm_update_tpi_key281(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key281

    integer function gmm_update_tpi_key241(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key241

    integer function gmm_update_tpi_key381(indx, key)
        integer, intent(in) :: indx
        integer*8, intent(in) :: key
    end function gmm_update_tpi_key381
end interface
