#include "rmn_build_info.h"

!FONCTION EXDB    IMPRESSION DE BOITE DE DEBUT D'EXECUTION

      INTEGER FUNCTION EXDB(in_TITRE,REVIS,FLAG)
      IMPLICIT NONE
      CHARACTER*(*) in_TITRE,REVIS,FLAG

      INTEGER EXDBPLUS
      EXTERNAL EXDBPLUS

      CHARACTER *90 UNUSEDSTRING
      EXDB=EXDBPLUS(in_TITRE,REVIS,FLAG,UNUSEDSTRING,0)
      RETURN
      END

!FONCTION EXDBPLUS    IMPRESSION DE BOITE DE DEBUT D'EXECUTION

      INTEGER FUNCTION EXDBPLUS(in_TITRE,REVIS,FLAG,SUPP,NSUP)
      use rmn_app
      IMPLICIT NONE
      INTEGER NSUP
      CHARACTER*(*) in_TITRE,REVIS,FLAG,SUPP(NSUP)

!AUTEUR  M.VALIN RPN MARS 1983
!Revision 002 M. Lepine Octobre 1998 - Ajout de la signature RMNLIB
!Revision 003 M. Lepine Octobre 2008 - Anciennement exdb, ajout de lignes d'impression
!                                      supplementaires en option
!Revision 004 M. Valin  Mars 2022    - eliminer l'enonce ENTRY pour EXFIN et 
!                                      en faire une fonction a part
!                                      suppression de format inutilise
!
!OBJET(EXDB)
!        IMPRIMER UNE BOITE INDIQUANT LE DEBUT DE L'EXECUTION
!        D'UN PROGRAMME FORTRAN. EXDB RENVOIE EGALEMENT LE
!        DATE TIME STAMP (NOMBRE ENTIER DE 10 CHIFFRES) DE
!        LA PASSE OPERATIONNELLE COURANTE.
!
!ARGUMENTS
!  E     TITRE     CHAINE DE CARACTERES. SEULS LES 7 PREMIERS
!                  SERONT IMPRIMES.
!  E     REVIS     CHAINE DE CARACTERES INDIQUANT LA VERSION DU
!                  PRODUIT (EXDB) OU UN MESSAGE DE FIN (EXFIN). SEULS LES
!                  DIX PREMIERS CARACTERES SERONT IMPRIMES.
!  E     FLAG      IGNORE.  CONSERVE POUR COMPATIBILITE ARRIERE
!  E     SUPP      LIGNES D'INFORMATION SUPPLEMENTAIRE A IMPRIMER
!  E     NSUP      NOMBRE DE LIGNE SUPPLEMENTAIRES A IMPRIMER

!MESSAGES
!        EXDB ET EXFIN ECRIVENT SUR L'UNITE FORTRAN 6. L'USAGER
!        EST RESPONSABLE D'OUVRIR  CETTE UNITE CORRECTEMENT.

!MODULES
!        DATE      POUR OBTENIR LA DATE DU SYSTEME  (RMNLIB5)
!        DATMGP2   POUR RECONSTITUER LE DATE TIME STAMP  (RMNLIB5)
!        TIME      POUR OBTENIR L'HEURE  (LIBRAIRIE FORTRAN)

!NOTES
!        EXDB VA CHERCHER DANS RA+56 A RA+63 L'IMAGE DE LA CARTE
!        DE CONTROLE QUI A SERVI A APPELER LE PROGRAMME PRINCIPAL.
!        CECI EST UNE DEPENDANCE CDC  (NOS OU SCOPE 2)
!        EXDB SE SERT DU FICHIER FORTRAN 88, L'OUVRE ET LE
!        RETOURNE.

      app_ptr=app_init(APP_MASTER,in_TITRE,REVIS,'',BUILD_TIMESTAMP)
      call app_start()

     EXDBPLUS = 0

      RETURN
      END

!FONCTION EXDBPLUS    IMPRESSION DE BOITE DE FIN D'EXECUTION
      INTEGER FUNCTION EXFIN(in_TITRE,REVIS,FLAG)
      use rmn_app
      IMPLICIT NONE
      CHARACTER*(*) in_TITRE,REVIS,FLAG
!AUTEUR  M.VALIN RPN MARS 2022

!OBJET(EXFIN)
!        EXFIN IMPRIME UNE BOITE INDIQUANT LA FIN DE L'EXECUTION
!        D'UN PROGRAMME FORTRAN. LA VALEUR RENVOYEE EST ZERO.
!ARGUMENTS
!  E     TITRE     voir EXDB
!  E     REVIS     voir EXDB
!  E     FLAG      inutilise, garde par compatibilite arriere
!NOTES
!     autrefois un ENTRY dans EXDBPLUS, maintenant une fonction `a part

      EXFIN=app_end(-1)

      RETURN
      END
